/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2025-06-17 03:04:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 푸터 -->\r\n");
      out.write("	<footer>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footerTopWrap\">\r\n");
      out.write("			<div class=\"footerListwrapOne\">\r\n");
      out.write("				<div class=\"noticeWrap\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<h4>\r\n");
      out.write("							<a href=\"\">공지사항 &nbsp;&gt;</a>\r\n");
      out.write("						</h4>\r\n");
      out.write("						<li><a href=\"#\">&nbsp; 4월 신용카드 무이자 안내</a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>&nbsp; [채용공고] 빌링 서비스 백엔드 개발자</span></a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>&nbsp; [채용공고] 백엔드 엔지니어</span></a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>&nbsp; [채용공고] IT서비스 개발팀장</span></a></li>\r\n");
      out.write("						<li><a href=\"#\" style=\"color: orange;\">&nbsp;\r\n");
      out.write("								구형크레마(안드로이드4.4이하) 앱서비스 지원 종료,보상 판매 안내</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"searchWrap\">\r\n");
      out.write("					<h4>검색</h4>\r\n");
      out.write("					<div class=\"searchBoxWrap\">\r\n");
      out.write("						<input class=\"search\" type=\"text\">\r\n");
      out.write("						<button>\r\n");
      out.write("							<img src=\"img/button/searchIcon.png\" alt=\"searchIcon\">\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"radio\" name=\"search\" value=\"FAQ\" class=\"searchRadio\"\r\n");
      out.write("						checked>\r\n");
      out.write("					<p>FAQ</p>\r\n");
      out.write("					<input type=\"radio\" name=\"search\" value=\"공지사항\" class=\"searchRadio\">\r\n");
      out.write("					<p>공지사항</p>\r\n");
      out.write("					<input type=\"radio\" name=\"search\" value=\"당첨자발표\" class=\"searchRadio\">\r\n");
      out.write("					<p>당첨자발표</p>\r\n");
      out.write("					<input type=\"radio\" name=\"search\" value=\"서비스안내\" class=\"searchRadio\">\r\n");
      out.write("					<p>서비스안내</p>\r\n");
      out.write("\r\n");
      out.write("					<p class=\"eventWinner\">\r\n");
      out.write("						<a href=\"#\">이벤트 당첨자 발표 ></a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"fastServiceWrap\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<h4>빠른 서비스</h4>\r\n");
      out.write("						<li><a href=\"#\">반품/교환</a></li>\r\n");
      out.write("						<li><a href=\"#\">신청 증빙서류 신청</a></li>\r\n");
      out.write("						<li><a href=\"#\">미배송 신고</a></li>\r\n");
      out.write("						<li><a href=\"#\">입금신고</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"publisherWrap\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<h4>출판사, 판매자 안내</h4>\r\n");
      out.write("						<li><a href=\"#\">제휴 & 마케팅 안내</a></li>\r\n");
      out.write("						<li><a href=\"#\">출판사/공급사 안내</a></li>\r\n");
      out.write("						<li><a href=\"#\">광고 안내</a></li>\r\n");
      out.write("						<li><a href=\"#\">판매자 매니저</a></li>\r\n");
      out.write("						<li><a href=\"#\">학교/기업/기관 대량구매</a></li>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"footerListwrapTwo\">\r\n");
      out.write("				<div class=\"footerListBottom\">\r\n");
      out.write("					<div class=\"footerListBottomTitle\">스페셜 서비스</div>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">독자북펀드</a></li>\r\n");
      out.write("						<li><a href=\"#\">알라딘 멤버십</a></li>\r\n");
      out.write("						<li><a href=\"#\">선물하기 / 선물상품권</a></li>\r\n");
      out.write("						<li><a href=\"#\">알라딘 US</a></li>\r\n");
      out.write("						<li><a href=\"#\">알림센터</a></li>\r\n");
      out.write("						<li><a href=\"#\">품절도서센터</a></li>\r\n");
      out.write("						<li><a href=\"#\">알라딘 캐시</a></li>\r\n");
      out.write("						<li><a href=\"#\">전자책 캐시</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footerListBottom\">\r\n");
      out.write("					<div class=\"footerListBottomTitle\">가격 만족</div>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">2천원 추가 마일리지</a></li>\r\n");
      out.write("						<li><a href=\"#\">Thanks to 적립금</a></li>\r\n");
      out.write("						<li><a href=\"#\">최저가격 계산기</a></li>\r\n");
      out.write("						<li><a href=\"#\">최저가 보상제도</a></li>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footerListBottom\">\r\n");
      out.write("					<div class=\"footerListBottomTitle\">배송 만족</div>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">양탄자배송/당일배송</a></li>\r\n");
      out.write("						<li><a href=\"#\">편의점 배송</a></li>\r\n");
      out.write("						<li><a href=\"#\">수령일 예고제</a></li>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footerListBottom\">\r\n");
      out.write("					<div class=\"footerListBottomTitle\">블로그 & SNS</div>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">알라딘 북플</a></li>\r\n");
      out.write("						<li><a href=\"#\">알라딘 서재</a></li>\r\n");
      out.write("						<li><a href=\"#\">알라딘 트위터</a></li>\r\n");
      out.write("						<li><a href=\"#\">알라딘 페이스북</a></li>\r\n");
      out.write("						<li><a href=\"#\">알라딘 인스타그램</a></li>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footerListBottom\">\r\n");
      out.write("					<div class=\"footerListBottomTitle\">웹 & 모바일</div>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">Open API</a></li>\r\n");
      out.write("						<li><a href=\"#\">모바일/앱</a></li>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footerListBottom\">\r\n");
      out.write("					<div class=\"footerListBottomTitle\">제휴 서비스</div>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">문화상품권(지류/온라인)</a></li>\r\n");
      out.write("						<li><a href=\"#\">컬쳐랜드상품권</a></li>\r\n");
      out.write("						<li><a href=\"#\">아시아나항공 마일리지</a></li>\r\n");
      out.write("						<li><a href=\"#\">에쓰오일 S포인트</a></li>\r\n");
      out.write("						<li><a href=\"#\">문화누리카드</a></li>\r\n");
      out.write("						<li><a href=\"#\">알라딘 전자도서관</a></li>\r\n");
      out.write("						<li><a href=\"#\">도서판매사업자 서비스</a></li>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--중간 푸터 시작-->\r\n");
      out.write("		<div class=\"footerMiddleWrap\">\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"#\">회사소개</a>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"#\">채용안내</a>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"#\">이용약관</a>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"#\"><strong>개인정보처리방침</strong></a>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"#\">청소년 보호정책</a>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"#\">중고매장</a>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"#\">제휴·마케팅 안내</a>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"#\">판매자 매니저</a>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"#\">출판사·공급사 안내</a>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"#\">광고안내</a>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a href=\"#\">학교·기업·기관 대량구매</a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--중간 푸터 끝-->\r\n");
      out.write("		<!--하단 푸터 시작-->\r\n");
      out.write("		<div class=\"footerBottomWrap\">\r\n");
      out.write("			<div class=\"aladinCommunicationWrap\">\r\n");
      out.write("				<h3>(주)알라딘커뮤니케이션</h3>\r\n");
      out.write("				<p>대표이사 최우경\r\n");
      out.write("				<p>\r\n");
      out.write("				<p>고객정보보호 책임자 최우경</p>\r\n");
      out.write("				<p>\r\n");
      out.write("					<a href=\"#\">사업자등록 201-81-23094 ></a>\r\n");
      out.write("				</p>\r\n");
      out.write("				<p>통신판매업신고 2003-서울중구-01520</p>\r\n");
      out.write("				<br>\r\n");
      out.write("				<p>이메일 privacy@aladin.co.kr</p>\r\n");
      out.write("				<p>호스팅 제공자 알라딘커뮤니케이션</p>\r\n");
      out.write("				<p>(본사) 서울시 중구 서소문로 89-31</p>\r\n");
      out.write("				<br>\r\n");
      out.write("				<p>ⓒ Aladin Communication. All Rights Reserved.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"customerServiceWrap\">\r\n");
      out.write("				<h3>고객센터 1544-2514 (발신자 부담)</h3>\r\n");
      out.write("				<p>서울시 마포구 백범로 71 숨도빌딩 7층 Fax 02-6926-2600</p>\r\n");
      out.write("				<a href=\"#\">\r\n");
      out.write("					<div class=\"customerServiceInqueryFaq\">1:1 문의</div>\r\n");
      out.write("				</a> <a href=\"#\">\r\n");
      out.write("					<div class=\"customerServiceInqueryFaq\">FAQ</div>\r\n");
      out.write("				</a> <a href=\"#\">\r\n");
      out.write("					<div class=\"storeLocation\">중고매장 위치. 영업시간 안내</div>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--하단 푸터 끝-->\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- 푸터 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
