/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2025-06-22 13:10:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.aladin.dto.MemberVO;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1750043283463L));
    _jspx_dependants.put("jar:file:/C:/java_work/aladin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aladin/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/java_work/aladin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aladin/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.aladin.dto.MemberVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 헤더 시작-->\r\n");
      out.write("	<header>\r\n");
      out.write("		<!--헤더 카테고리 시작-->\r\n");
      out.write("		<div class=\"headerCategoryWrap\">\r\n");
      out.write("			<div class=\"categoryLogin\">\r\n");
      out.write("				<div class=\"headerCategory\">\r\n");
      out.write("					<ul class=\"bookCategory\">\r\n");
      out.write("						<li class=\"homeMenu\"><a href=\"#\">HOME</a></li>\r\n");
      out.write("						<li class=\"bookCategoryBig\"><a href=\"#\">국내도서</a>\r\n");
      out.write("							<div class=\"menuBoxKorea\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"#\">국내도서&nbsp&gt</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">건강/취미</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>경제경영</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">공무원 수험서</a></li>\r\n");
      out.write("									<li><a href=\"#\">과학</a></li>\r\n");
      out.write("									<li><a href=\"#\">달력/기타</a></li>\r\n");
      out.write("									<li><a href=\"#\">대학교재</a></li>\r\n");
      out.write("									<li><a href=\"#\">만화</a></li>\r\n");
      out.write("									<li><a href=\"#\">사회과학</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>소설/시/희곡</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>수험서/자격증</strong></a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\"><strong>어린이</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">에세이</a></li>\r\n");
      out.write("									<li><a href=\"#\">여행</a></li>\r\n");
      out.write("									<li><a href=\"#\">역사</a></li>\r\n");
      out.write("									<li><a href=\"#\">예술/대중문화</a></li>\r\n");
      out.write("									<li><a href=\"#\">외국어</a></li>\r\n");
      out.write("									<li><a href=\"#\">요리/살림</a></li>\r\n");
      out.write("									<li><a href=\"#\">유아</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>인문학</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">자기계발</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">잡지</a></li>\r\n");
      out.write("									<li><a href=\"#\">장르소설</a></li>\r\n");
      out.write("									<li><a href=\"#\">전집/중고전집</a></li>\r\n");
      out.write("									<li><a href=\"#\">종교/역학</a></li>\r\n");
      out.write("									<li><a href=\"#\">좋은부모</a></li>\r\n");
      out.write("									<li><a href=\"#\">청소년</a></li>\r\n");
      out.write("									<li><a href=\"#\">컴퓨터/모바일</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>초등학교참고서</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">중학교참고서</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>고등학교참고서</strong></a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">베스트셀러</a></li>\r\n");
      out.write("									<li><a href=\"#\">새로나온책</a></li>\r\n");
      out.write("									<li><a href=\"#\">재정가도서</a></li>\r\n");
      out.write("									<li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("									<li><a href=\"#\">독자북펀드</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<div class=\"advertiseBanner\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						<li class=\"bookCategoryBig\"><a href=\"#\">외국도서</a>\r\n");
      out.write("							<div class=\"menuBoxforeign\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"#\">외국도서&nbsp&gt</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\"><strong>영미도서</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">ELT/어학/사전</a></li>\r\n");
      out.write("									<li><a href=\"#\">가정/원예/인테리어</a></li>\r\n");
      out.write("									<li><a href=\"#\">건강/스포츠</a></li>\r\n");
      out.write("									<li><a href=\"#\">경제경영</a></li>\r\n");
      out.write("									<li><a href=\"#\">공예/취미/수집</a></li>\r\n");
      out.write("									<li><a href=\"#\">만화</a></li>\r\n");
      out.write("									<li><a href=\"#\">소설/시/희곡</a></li>\r\n");
      out.write("									<li><a href=\"#\">여행</a></li>\r\n");
      out.write("									<li><a href=\"#\">역사</a></li>\r\n");
      out.write("									<li><a href=\"#\">요리</a></li>\r\n");
      out.write("									<li><a href=\"#\">인문/사회</a></li>\r\n");
      out.write("									<li><a href=\"#\">종교/명상/점술</a></li>\r\n");
      out.write("									<li><a href=\"#\">청소년</a></li>\r\n");
      out.write("									<li><a href=\"#\">해외잡지</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\"><strong>대학교재/전문서</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">건축/디자인</a></li>\r\n");
      out.write("									<li><a href=\"#\">교육/자료</a></li>\r\n");
      out.write("									<li><a href=\"#\">기술공학</a></li>\r\n");
      out.write("									<li><a href=\"#\">법률</a></li>\r\n");
      out.write("									<li><a href=\"#\">수험서</a></li>\r\n");
      out.write("									<li><a href=\"#\">언어학</a></li>\r\n");
      out.write("									<li><a href=\"#\">예술/대중문화</a></li>\r\n");
      out.write("									<li><a href=\"#\">의학</a></li>\r\n");
      out.write("									<li><a href=\"#\">자연과학</a></li>\r\n");
      out.write("									<li><a href=\"#\">컴퓨터</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\"><strong>기타언어권</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">독일 도서</a></li>\r\n");
      out.write("									<li><a href=\"#\">스페인 도서</a></li>\r\n");
      out.write("									<li><a href=\"#\">중국 도서</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\"><strong>어린이</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">그림책</a></li>\r\n");
      out.write("									<li><a href=\"#\">동화책</a></li>\r\n");
      out.write("									<li><a href=\"#\">리더스</a></li>\r\n");
      out.write("									<li><a href=\"#\">영어학습</a></li>\r\n");
      out.write("									<li><a href=\"#\">챕터북</a></li>\r\n");
      out.write("									<li><a href=\"#\">코스북</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\"><strong>일본도서</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">문학</a></li>\r\n");
      out.write("									<li><a href=\"#\">애니메이션 굿즈</a></li>\r\n");
      out.write("									<li><a href=\"#\">잡지</a></li>\r\n");
      out.write("									<li><a href=\"#\">코믹</a></li>\r\n");
      out.write("									<li><a href=\"#\">베스트셀러</a></li>\r\n");
      out.write("									<li><a href=\"#\">새로나온책</a></li>\r\n");
      out.write("									<li><a href=\"#\">특가도서</a></li>\r\n");
      out.write("									<li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("									<li><a href=\"#\" style=\"color: #f32383\"><strong>LEXILE\r\n");
      out.write("												지수별 <br>원서 읽기\r\n");
      out.write("										</strong></a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<div class=\"advertiseBanner\"></div>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li class=\"bookCategoryBig\"><a href=\"#\">전자책</a>\r\n");
      out.write("							<div class=\"menuBoxeBook\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"#\">eBook&nbsp&gt</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">건강/취미</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>경제경영</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">과학</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>라이트노벨</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>로맨스</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>만화</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\"> <pstrong>사회과학</pstrong>\r\n");
      out.write("									</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>소설/시/희곡</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">어린이</a></li>\r\n");
      out.write("\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\"><strong>에세이</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">여행</a></li>\r\n");
      out.write("									<li><a href=\"#\">역사</a></li>\r\n");
      out.write("									<li><a href=\"#\">예술/대중문화</a></li>\r\n");
      out.write("									<li><a href=\"#\">외국어</a></li>\r\n");
      out.write("									<li><a href=\"#\">요리/살림</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>인문학</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>자기계발</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">좋은부모</a></li>\r\n");
      out.write("									<li><a href=\"#\">청소년</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">판타지/무협</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>BL</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>오디오북</strong></a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">베스트셀러</a></li>\r\n");
      out.write("									<li><a href=\"#\">새로나온eBook</a></li>\r\n");
      out.write("									<li><a href=\"#\">대여eBook</a></li>\r\n");
      out.write("									<li><a href=\"#\">연재eBook</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<div class=\"advertiseBanner\"></div>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li class=\"bookCategoryBig\"><a href=\"#\">알라딘굿즈</a>\r\n");
      out.write("							<div class=\"goods\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"#\">알라딘굿즈&nbsp&gt</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">가방,파우치</a></li>\r\n");
      out.write("									<li><a href=\"#\">데스크용품</a></li>\r\n");
      out.write("									<li><a href=\"#\">독서용품</a></li>\r\n");
      out.write("									<li><a href=\"#\">디지털</a></li>\r\n");
      out.write("									<li><a href=\"#\">리빙,키친</a></li>\r\n");
      out.write("									<li><a href=\"#\">문구</a></li>\r\n");
      out.write("									<li><a href=\"#\">생활용품</a></li>\r\n");
      out.write("									<li><a href=\"#\">의류·잡화</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">노트</a></li>\r\n");
      out.write("									<li><a href=\"#\">독서대</a></li>\r\n");
      out.write("									<li><a href=\"#\">북마크</a></li>\r\n");
      out.write("									<li><a href=\"#\">북커버</a></li>\r\n");
      out.write("									<li><a href=\"#\">사무용품</a></li>\r\n");
      out.write("									<li><a href=\"#\">조명</a></li>\r\n");
      out.write("									<li><a href=\"#\">파우치</a></li>\r\n");
      out.write("									<li><a href=\"#\">필기구</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">피너츠</a></li>\r\n");
      out.write("									<li><a href=\"#\">어린왕자</a></li>\r\n");
      out.write("									<li><a href=\"#\">우주</a></li>\r\n");
      out.write("									<li><a href=\"#\">앨리스</a></li>\r\n");
      out.write("									<li><a href=\"#\">빨강머리 앤</a></li>\r\n");
      out.write("									<li><a href=\"#\">고양이</a></li>\r\n");
      out.write("									<li><a href=\"#\">모비딕</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">베스트셀러</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>생활용품연구소</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">알라딘 문방구</a></li>\r\n");
      out.write("									<li><a href=\"#\">굿즈한정할인</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<div class=\"advertiseBanner\"></div>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li class=\"bookCategoryBig\"><a href=\"#\">온라인중고</a>\r\n");
      out.write("							<div class=\"onlineUsed\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"#\">온라인중고&nbsp&gt</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">경제경영</a></li>\r\n");
      out.write("									<li><a href=\"#\">만화</a></li>\r\n");
      out.write("									<li><a href=\"#\">사회과학</a></li>\r\n");
      out.write("									<li><a href=\"#\">소설/시/희곡</a></li>\r\n");
      out.write("									<li><a href=\"#\">수험서/자격증</a></li>\r\n");
      out.write("									<li><a href=\"#\">어린이</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>에세이</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">역사</a></li>\r\n");
      out.write("									<li><a href=\"#\">예술/대중문화</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">외국어</a></li>\r\n");
      out.write("									<li><a href=\"#\">요리/살림</a></li>\r\n");
      out.write("									<li><a href=\"#\">유아</a></li>\r\n");
      out.write("									<li><a href=\"#\">인문학</a></li>\r\n");
      out.write("									<li><a href=\"#\">자기계발</a></li>\r\n");
      out.write("									<li><a href=\"#\">종교/역학</a></li>\r\n");
      out.write("									<li><a href=\"#\">좋은부모</a></li>\r\n");
      out.write("									<li><a href=\"#\">청소년</a></li>\r\n");
      out.write("									<li><a href=\"#\">컴퓨터/모바일</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">잡지</a></li>\r\n");
      out.write("									<li><a href=\"#\">장르소설</a></li>\r\n");
      out.write("									<li><a href=\"#\">전집/중고전집</a></li>\r\n");
      out.write("									<li><a href=\"#\">종교/역학</a></li>\r\n");
      out.write("									<li><a href=\"#\">좋은부모</a></li>\r\n");
      out.write("									<li><a href=\"#\">청소년</a></li>\r\n");
      out.write("									<li><a href=\"#\">컴퓨터/모바일</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>초등학교참고서</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">중학교참고서</a></li>\r\n");
      out.write("									<li><a href=\"#\"><strong>고등학교참고서</strong></a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">베스트셀러</a></li>\r\n");
      out.write("									<li><a href=\"#\">새로나온책</a></li>\r\n");
      out.write("									<li><a href=\"#\">재정가도서</a></li>\r\n");
      out.write("									<li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("									<li><a href=\"#\">독자북펀드</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<div class=\"advertiseBanner\"></div>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li class=\"bookCategoryBig\"><a href=\"#\">우주점</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"bookCategoryBig\"><a href=\"#\">중고매장</a>\r\n");
      out.write("							<div class=\"usedStore\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"#\">중고매장&nbsp&gt</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\"><strong>서울</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">가로수길점</a></li>\r\n");
      out.write("									<li><a href=\"#\">강남점</a></li>\r\n");
      out.write("									<li><a href=\"#\">강서홈플러스점</a></li>\r\n");
      out.write("									<li><a href=\"#\">건대점</a></li>\r\n");
      out.write("									<li><a href=\"#\">구로디지털단지역점</a></li>\r\n");
      out.write("									<li><a href=\"#\">노원역점</a></li>\r\n");
      out.write("									<li><a href=\"#\">대학로점</a></li>\r\n");
      out.write("									<li><a href=\"#\">목동점</a></li>\r\n");
      out.write("									<li><a href=\"#\">서울대입구역점</a></li>\r\n");
      out.write("									<li><a href=\"#\">수유점</a></li>\r\n");
      out.write("									<li><a href=\"#\">신논현점</a></li>\r\n");
      out.write("									<li><a href=\"#\">신림점</a></li>\r\n");
      out.write("									<li><a href=\"#\">신촌점</a></li>\r\n");
      out.write("									<li><a href=\"#\">연신내점</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<br>\r\n");
      out.write("									<li><a href=\"#\">영등포점</a></li>\r\n");
      out.write("									<li><a href=\"#\">이수역점</a></li>\r\n");
      out.write("									<li><a href=\"#\">잠실롯데월드타워점</a></li>\r\n");
      out.write("									<li><a href=\"#\">잠실새내역점</a></li>\r\n");
      out.write("									<li><a href=\"#\">종로점</a></li>\r\n");
      out.write("									<li><a href=\"#\">천호점</a></li>\r\n");
      out.write("									<li><a href=\"#\">합정점</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\"><strong>경기</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">동탄2하나로마트점</a></li>\r\n");
      out.write("									<li><a href=\"#\">동탄점</a></li>\r\n");
      out.write("									<li><a href=\"#\">범계점</a></li>\r\n");
      out.write("									<li><a href=\"#\">부천점</a></li>\r\n");
      out.write("									<li><a href=\"#\">분당서현점</a></li>\r\n");
      out.write("									<li><a href=\"#\">분당야탑점</a></li>\r\n");
      out.write("									<li><a href=\"#\">산본점</a></li>\r\n");
      out.write("									<li><a href=\"#\">수원시청역점</a></li>\r\n");
      out.write("									<li><a href=\"#\">수원점</a></li>\r\n");
      out.write("									<li><a href=\"#\">수지점</a></li>\r\n");
      out.write("									<li><a href=\"#\">안산고잔점</a></li>\r\n");
      out.write("									<li><a href=\"#\">의정부홈플러스점</a></li>\r\n");
      out.write("									<li><a href=\"#\">일산점</a></li>\r\n");
      out.write("									<li><a href=\"#\">평택점</a></li>\r\n");
      out.write("									<li><a href=\"#\">화정점</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\"><strong>광역시 등</strong></a></li>\r\n");
      out.write("									<li><a href=\"#\">광주상무점</a></li>\r\n");
      out.write("									<li><a href=\"#\">광주충장로점</a></li>\r\n");
      out.write("									<li><a href=\"#\">김해점</a></li>\r\n");
      out.write("									<li><a href=\"#\">대구동성로점</a></li>\r\n");
      out.write("									<li><a href=\"#\">대구상인점</a></li>\r\n");
      out.write("									<li><a href=\"#\">대전시청역점</a></li>\r\n");
      out.write("									<li><a href=\"#\">대전은행점</a></li>\r\n");
      out.write("									<li><a href=\"#\">동대구역점</a></li>\r\n");
      out.write("									<li><a href=\"#\">마산합성점</a></li>\r\n");
      out.write("									<li><a href=\"#\">부산경성대 부경대역점</a></li>\r\n");
      out.write("									<li><a href=\"#\">부산덕천점</a></li>\r\n");
      out.write("									<li><a href=\"#\">부산서면점</a></li>\r\n");
      out.write("									<li><a href=\"#\">무산센텀점</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<br>\r\n");
      out.write("									<li><a href=\"#\">울산점</a></li>\r\n");
      out.write("									<li><a href=\"#\">인천계산점</a></li>\r\n");
      out.write("									<li><a href=\"#\">인천구월점</a></li>\r\n");
      out.write("									<li><a href=\"#\">인천송도점</a></li>\r\n");
      out.write("									<li><a href=\"#\">인천청라점</a></li>\r\n");
      out.write("									<li><a href=\"#\">전주점</a></li>\r\n");
      out.write("									<li><a href=\"#\">창원상남점</a></li>\r\n");
      out.write("									<li><a href=\"#\">천안신불당점</a></li>\r\n");
      out.write("									<li><a href=\"#\">청주점</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<div class=\"advertiseBanner\"></div>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li class=\"bookCategoryBig\"><a href=\"#\">커피</a>\r\n");
      out.write("							<div class=\"coffee\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"#\">커피&nbsp&gt</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">커피</a></li>\r\n");
      out.write("									<li><a href=\"#\">드립백</a></li>\r\n");
      out.write("									<li><a href=\"#\">콜드브루</a></li>\r\n");
      out.write("									<li><a href=\"#\">커피도구</a></li>\r\n");
      out.write("									<li><a href=\"#\">스탬프 이벤트</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#\">매장 메뉴</a></li>\r\n");
      out.write("									<li><a href=\"#\">커피 매장</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"bookCategoryBig\"><a href=\"#\">블루레이</a>\r\n");
      out.write("									<div class=\"blueRay\">\r\n");
      out.write("										<h3>\r\n");
      out.write("											<a href=\"#\">블루레이 &nbsp&gt</a>\r\n");
      out.write("										</h3>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a href=\"#\">블루레이</a></li>\r\n");
      out.write("											<li><a href=\"#\">3D 블루레이</a></li>\r\n");
      out.write("											<li><a href=\"#\">공포/스릴러</a></li>\r\n");
      out.write("											<li><a href=\"#\">다큐멘터리</a></li>\r\n");
      out.write("											<li><a href=\"#\">드라마/코미디</a></li>\r\n");
      out.write("											<li><a href=\"#\">애니메이션</a></li>\r\n");
      out.write("											<li><a href=\"#\">액션/SF</a></li>\r\n");
      out.write("											<li><a href=\"#\">음악</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<br>\r\n");
      out.write("											<li><a href=\"#\"><strong>DVD</strong></a></li>\r\n");
      out.write("											<li><a href=\"#\">공포/스릴러</a></li>\r\n");
      out.write("											<li><a href=\"#\">교양/다큐멘터리</a></li>\r\n");
      out.write("											<li><a href=\"#\">드라마/코미디</a></li>\r\n");
      out.write("											<li><a href=\"#\">박스세트</a></li>\r\n");
      out.write("											<li><a href=\"#\">성인</a></li>\r\n");
      out.write("											<li><a href=\"#\">애니메이션</a></li>\r\n");
      out.write("											<li><a href=\"#\">액션/어드벤쳐</a></li>\r\n");
      out.write("											<li><a href=\"#\">유아/아동</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<br>\r\n");
      out.write("											<br>\r\n");
      out.write("											<li><a href=\"#\">음악DVD</a></li>\r\n");
      out.write("											<li><a href=\"#\">제작국가별</a></li>\r\n");
      out.write("											<li><a href=\"#\">취미/스포츠</a></li>\r\n");
      out.write("											<li><a href=\"#\">S.F./판타지</a></li>\r\n");
      out.write("											<li><a href=\"#\">TV시리즈</a></li>\r\n");
      out.write("											<li><a href=\"#\">VCD</a></li>\r\n");
      out.write("											<li><a href=\"#\">VHS</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<br>\r\n");
      out.write("											<br>\r\n");
      out.write("											<li><a href=\"#\">베스트셀러</a></li>\r\n");
      out.write("											<li><a href=\"#\">예약 블루레이</a></li>\r\n");
      out.write("											<li><a href=\"#\">새로나온 블루레이</a></li>\r\n");
      out.write("											<li><a href=\"#\">예약알림 신청</a></li>\r\n");
      out.write("											<li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("											<li><a href=\"#\">초특가아울렛</a></li>\r\n");
      out.write("											<li><a href=\"#\">단독특가</a></li>\r\n");
      out.write("											<li><a href=\"#\">중고블루레이</a></li>\r\n");
      out.write("										</ul></li>\r\n");
      out.write("								<li class=\"bookCategoryBig\"><a href=\"#\">북플 ·</a></li>\r\n");
      out.write("								<li style=\"float: right;\">\r\n");
      out.write("									<div class=\"loginBox\">\r\n");
      out.write("										<ul class=\"loginul\">\r\n");
      out.write("											<!-- 로그인 정보 확인 -->\r\n");
      out.write("\r\n");
      out.write("											\r\n");
      out.write("											");

											MemberVO loginUser = (MemberVO) session.getAttribute("loginUser");
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("											<li><a href=\"#\">장바구니</a></li>\r\n");
      out.write("\r\n");
      out.write("											");

											if (loginUser != null) { // 세션이 있다면 (로그인되어 있다면)
											
      out.write("\r\n");
      out.write("											");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("											<li><a href=\"#\" onclick=\"location.href='boarderlist.do'\">고객센터</a></li>\r\n");
      out.write("											<li><a href=\"#\" onclick=\"location.href='mypage.do'\">마이페이지</a></li>\r\n");
      out.write("											<li><a href=\"#\" onclick=\"location.href='logout.do'\">로그아웃</a></li>\r\n");
      out.write("											<li>");
      out.print(loginUser.getUsername());
      out.write("님 안녕하세요.</li>\r\n");
      out.write("\r\n");
      out.write("											");

											} else { // 세션이 없다면
											
      out.write("\r\n");
      out.write("											<li><a href=\"#\" onclick=\"login()\">고객센터</a></li>\r\n");
      out.write("											<li><a href=\"#\" onclick=\"login()\">마이페이지</a></li>\r\n");
      out.write("											<li><a href=\"#\" onclick=\"location.href='join.do'\">회원가입</a></li>\r\n");
      out.write("											<li><a href=\"#\" onclick=\"login()\">로그인</a></li>\r\n");
      out.write("											");

											}
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("							</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				<!--헤더 카테고리 끝-->\r\n");
      out.write("\r\n");
      out.write("				<!--로고 및 검색창 시작-->\r\n");
      out.write("				<div class=\"headerMiddle\">\r\n");
      out.write("					<div class=\"logo_search\">\r\n");
      out.write("						<div class=\"logo\">\r\n");
      out.write("							<a href=\"#\" onclick=\"location.href='index.do'\"><img\r\n");
      out.write("								src=\"img/logo/aladin_logo.jpg\" alt=\"aladin_logo\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"searchField\">\r\n");
      out.write("							<div class=\"searchBox\">\r\n");
      out.write("								<select name=\"search\" id=\"search\">\r\n");
      out.write("									<option value=\"all\">통합검색&nbsp&nbsp&nbsp&nbsp</option>\r\n");
      out.write("									<option value=\"korea\">국내도서&nbsp&nbsp&nbsp&nbsp</option>\r\n");
      out.write("								</select> <input class=\"search\" type=\"text\" name=\"search\"\r\n");
      out.write("									placeholder=\"검색어를 입력하세요.\">\r\n");
      out.write("								<button value=\"search\">검색</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a href=\"#\">상세검색</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"headerBottom\">\r\n");
      out.write("					<div class=\"fieldViews\">\r\n");
      out.write("						<ul class=\"fieldCategory\">\r\n");
      out.write("							<li class=\"totalCategory\"><a href=\"#\"><img\r\n");
      out.write("									src=\"img/button/three_mark.jpt.JPG\" alt=\"three_mark\">&nbsp;분야보기</a>\r\n");
      out.write("								<div class=\"allCategory\">\r\n");
      out.write("									<div class=\"allCategoryKoreaGoodsForeign\">\r\n");
      out.write("										<div class=\"korea\">\r\n");
      out.write("											<div class=\"categoryTitle\">\r\n");
      out.write("												<a href=\"\">국내도서</a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\">건강/취미</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>경제경영</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">공무원 수험서</a></li>\r\n");
      out.write("												<li><a href=\"#\">과학</a></li>\r\n");
      out.write("												<li><a href=\"#\">달력/기타</a></li>\r\n");
      out.write("												<li><a href=\"#\">대학교재</a></li>\r\n");
      out.write("												<li><a href=\"#\">만화</a></li>\r\n");
      out.write("												<li><a href=\"#\">사회과학</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>소설/시/희곡</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>수험서/자격증</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>어린이</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">에세이</a></li>\r\n");
      out.write("												<li><a href=\"#\">여행</a></li>\r\n");
      out.write("												<li><a href=\"#\">역사</a></li>\r\n");
      out.write("												<li><a href=\"#\">예술/대중문화</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\">외국어</a></li>\r\n");
      out.write("												<li><a href=\"#\">요리/살림</a></li>\r\n");
      out.write("												<li><a href=\"#\">유아</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>인문학</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">자기계발</a></li>\r\n");
      out.write("												<li><a href=\"#\">잡지</a></li>\r\n");
      out.write("												<li><a href=\"#\">장르소설</a></li>\r\n");
      out.write("												<li><a href=\"#\">전집/중고전집</a></li>\r\n");
      out.write("												<li><a href=\"#\">종교/역학</a></li>\r\n");
      out.write("												<li><a href=\"#\">좋은부모</a></li>\r\n");
      out.write("												<li><a href=\"#\">청소년</a></li>\r\n");
      out.write("												<li><a href=\"#\">컴퓨터/모바일</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>초등학교참고서</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">중학교참고서</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>고등학교참고서</strong></a></li>\r\n");
      out.write("												<li>&nbsp;</li>\r\n");
      out.write("											</ul>\r\n");
      out.write("											<div class=\"categoryTitle\">\r\n");
      out.write("												<a href=\"\">알라딘 굿즈</a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\">가방 파우치</a></li>\r\n");
      out.write("												<li><a href=\"#\">데스크용품</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>독서용품</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">디지털</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\"><strong>문구</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">생활용품</a></li>\r\n");
      out.write("												<li><a href=\"#\">의류.잡화</a></li>\r\n");
      out.write("												<li><a href=\"#\">리빙.키친</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"allCategoryKoreaGoodsForeign\">\r\n");
      out.write("										<div class=\"korea\">\r\n");
      out.write("											<div class=\"categoryTitle\">\r\n");
      out.write("												<a href=\"\">외국도서</a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\"><strong>영미도서</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">ELT/어학/사전</a></li>\r\n");
      out.write("												<li><a href=\"#\">가정/원예/인테리어</a></li>\r\n");
      out.write("												<li><a href=\"#\">건강/스포츠</a></li>\r\n");
      out.write("												<li><a href=\"#\">경제경영</a></li>\r\n");
      out.write("												<li><a href=\"#\">공예/취미/수집</a></li>\r\n");
      out.write("												<li><a href=\"#\">만화</a></li>\r\n");
      out.write("												<li><a href=\"#\">소설/시/희곡</a></li>\r\n");
      out.write("												<li><a href=\"#\">여행</a></li>\r\n");
      out.write("												<li><a href=\"#\">역사</a></li>\r\n");
      out.write("												<li><a href=\"#\">요리</a></li>\r\n");
      out.write("												<li><a href=\"#\">인문/사회</a></li>\r\n");
      out.write("												<li><a href=\"#\">종교/명상/점술</a></li>\r\n");
      out.write("												<li><a href=\"#\">청소년</a></li>\r\n");
      out.write("												<li><a href=\"#\">해외잡지</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>일본도서</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">문학</a></li>\r\n");
      out.write("												<li><a href=\"#\">애니메이션 굿즈</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\"><strong>어린이</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">그림책</a></li>\r\n");
      out.write("												<li><a href=\"#\">동화책</a></li>\r\n");
      out.write("												<li><a href=\"#\">리더스</a></li>\r\n");
      out.write("												<li><a href=\"#\">영어학습</a></li>\r\n");
      out.write("												<li><a href=\"#\">챕터북</a></li>\r\n");
      out.write("												<li><a href=\"#\">코스북</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>중국도서</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">소설</a></li>\r\n");
      out.write("												<li><a href=\"#\">중국어 교재</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>기타 언어권</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">독일 도서</a></li>\r\n");
      out.write("												<li><a href=\"#\">베트남 도서</a></li>\r\n");
      out.write("												<li><a href=\"#\">스페인 도서</a></li>\r\n");
      out.write("												<li><a href=\"#\">프랑스 도서</a></li>\r\n");
      out.write("												<li><a href=\"#\">기타 도서</a></li>\r\n");
      out.write("												<li><a href=\"#\">잡지</a></li>\r\n");
      out.write("												<li><a href=\"#\">코믹</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"allCategoryEbookUsedMusic\">\r\n");
      out.write("										<div class=\"korea\">\r\n");
      out.write("											<div class=\"categoryTitle\">\r\n");
      out.write("												<a href=\"#\">eBook</a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\"><strong>경제경영</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>과학</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">라이트노벨</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>로맨스</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>만화</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">사회과학</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>소설/시</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">어린이</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>에세이</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">역사</a></li>\r\n");
      out.write("												<li><a href=\"#\">예술/대중문화</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>인문학</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>자기계발</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">종교/역학</a></li>\r\n");
      out.write("												<li><a href=\"#\">청소년</a></li>\r\n");
      out.write("												<li><a href=\"#\">판타지/무협</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>BL</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>오디오북</strong></a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"allCategoryEbookUsedMusic\">\r\n");
      out.write("										<div class=\"korea\">\r\n");
      out.write("											<div class=\"categoryTitle\">\r\n");
      out.write("												<a href=\"\">온라인중고</a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\" style=\"color: #f32383\"><strong>중고매장</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>중고 국내도서</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">경제경영</a></li>\r\n");
      out.write("												<li><a href=\"#\">만화</a></li>\r\n");
      out.write("												<li><a href=\"#\">사회과학</a></li>\r\n");
      out.write("												<li><a href=\"#\">소설/시/희곡</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>어린이</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">에세이</a></li>\r\n");
      out.write("												<li><a href=\"#\">유아</a></li>\r\n");
      out.write("												<li><a href=\"#\">인문학</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>중고음반</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">가요</a></li>\r\n");
      out.write("												<li><a href=\"#\">국악</a></li>\r\n");
      out.write("												<li><a href=\"#\">월드뮤직</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>클래식</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">팝</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>중고 DVD/블루레이</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>중고 외국도서</strong></a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"allCategoryEbookUsedMusic\">\r\n");
      out.write("										<div class=\"korea\">\r\n");
      out.write("											<div class=\"categoryTitle\">\r\n");
      out.write("												<a href=\"\">음반</a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\">가요</a></li>\r\n");
      out.write("												<li><a href=\"#\">국악</a></li>\r\n");
      out.write("												<li><a href=\"#\">월드뮤직</a></li>\r\n");
      out.write("												<li><a href=\"#\">재즈</a></li>\r\n");
      out.write("												<li><a href=\"#\">종교/명상/기타</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>클래식</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">팝</a></li>\r\n");
      out.write("												<li><a href=\"#\">J-POP</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>LP</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">OST</a></li>\r\n");
      out.write("												<li><a href=\"#\"></a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("											<div class=\"categoryTitle\">\r\n");
      out.write("												<a href=\"\">블루레이</a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\">공포/스릴러</a></li>\r\n");
      out.write("												<li><a href=\"#\">드라마/코미디</a></li>\r\n");
      out.write("												<li><a href=\"#\"><strong>블루레이</strong></a></li>\r\n");
      out.write("												<li><a href=\"#\">애니메이션</a></li>\r\n");
      out.write("												<li><a href=\"#\">액션/어드벤쳐</a></li>\r\n");
      out.write("												<li><a href=\"#\">음악DVD</a></li>\r\n");
      out.write("												<li><a href=\"#\">S.F./판타지</a></li>\r\n");
      out.write("												<li><a href=\"#\">TV시리즈</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div></li>\r\n");
      out.write("							<li><a href=\"#\" style=\"color: #a74c00;\">한강 에세이</a></li>\r\n");
      out.write("							<li><a href=\"#\">추천마법사</a></li>\r\n");
      out.write("							<li><a href=\"#\">베스트</a></li>\r\n");
      out.write("							<li><a href=\"#\">새로나온책</a></li>\r\n");
      out.write("							<li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("							<li><a href=\"#\">정가인하도서</a></li>\r\n");
      out.write("							<li class=\"recommendBook\"><a href=\"#\">추천도서&nbsp;</a></li>\r\n");
      out.write("							<li><a href=\"#\">작가와의 만남</a></li>\r\n");
      out.write("							<li><a href=\"#\">북펀드</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!--로고 및 검색창 끝-->\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- 헤더 끝-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Views/header.jsp(436,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.getAdmin() == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("												<li>관리자메뉴</li>\r\n");
          out.write("											");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
