/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2025-06-18 02:31:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>알라딘</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/slider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/smalSlider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/miniAdvertise.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/eventSlider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/bookFundSlider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/hangangSlider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/recommendMagicion.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/bookNewsSlider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/thisMonthSlider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/weekSaleSlider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/login.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 헤더 임포트 -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- 슬라이더 시작 -->\r\n");
      out.write("	<div id=\"slider\">\r\n");
      out.write("		<!-- 편집장의 선택 시작-->\r\n");
      out.write("		<div class=\"editorChoiceSlider\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"editorSlider\"></div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"eventSlider\">\r\n");
      out.write("						<div class=\"contentTwowrap\">\r\n");
      out.write("							<a href=\"#\"><img\r\n");
      out.write("								src=\"img/recommendEvent/recommendEvent_01.jpg\" alt=\"\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"contentTwowrap\">\r\n");
      out.write("							<a href=\"#\"><img\r\n");
      out.write("								src=\"img/recommendEvent/recommendEvent_02.jpg\" alt=\"\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"contentTwowrap\">\r\n");
      out.write("							<a href=\"#\"><img\r\n");
      out.write("								src=\"img/recommendEvent/recommendEvent_03.jpg\" alt=\"\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"thisWeekSlider\"></div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"newBookSlider\"></div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"eyeBookSlider\"></div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"popularBookSlider\"></div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"eventGoodsSlider\"></div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"bestBookSlider\"></div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"elecBookSlider\">\r\n");
      out.write("						<div class=\"contentTwowrap\">\r\n");
      out.write("							<img src=\"img/eBook/eBookSlider01.jpg\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"contentTwowrap\">\r\n");
      out.write("							<img src=\"img/eBook/eBookSlider02.jpg\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"contentTwowrap\">\r\n");
      out.write("							<img src=\"img/eBook/eBookSlider03.jpg\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<!-- 슬라이더 선텍 -->\r\n");
      out.write("			<div class=\"choiceSelector\">\r\n");
      out.write("				<div id=\"editorSelect\">편집장의 선택</div>\r\n");
      out.write("				<div id=\"event\">추천 이벤트</div>\r\n");
      out.write("				<div id=\"thisWeek\">이 주의 책</div>\r\n");
      out.write("				<div id=\"newBook\">신간 소개</div>\r\n");
      out.write("				<div id=\"eyeBook\">눈에 띄는 새책</div>\r\n");
      out.write("				<div id=\"popularBook\">화제의 책</div>\r\n");
      out.write("				<div id=\"eventGoods\">이벤트 굿즈</div>\r\n");
      out.write("				<div id=\"bestBook\">21세기 최고의 책</div>\r\n");
      out.write("				<div id=\"elecBook\">e Book</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 편집장의 선택 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--작은 슬라이더 시작-->\r\n");
      out.write("		<div class=\"smallSlider\">\r\n");
      out.write("			<div class=\"smallSliderButton\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"editorPick\"><a href=\"#\">편집장의 선택</a></li>\r\n");
      out.write("					<li class=\"smallSliderEbook\"><a href=\"#\">eBook</a></li>\r\n");
      out.write("					<li class=\"forignBook\"><a href=\"#\">외국도서</a></li>\r\n");
      out.write("					<li class=\"smallSliderNewbook\"><a href=\"#\">새로 나온 책</a></li>\r\n");
      out.write("					<li class=\"aladinGoods\"><a href=\"#\">올해의 책</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"smallSliderContent\">\r\n");
      out.write("				<div class=\"smallSliderContentOne\"></div>\r\n");
      out.write("				<div class=\"smallSliderContentTwo\"></div>\r\n");
      out.write("				<div class=\"smallSliderContentThree\"></div>\r\n");
      out.write("				<div class=\"smallSliderContentFour\"></div>\r\n");
      out.write("				<div class=\"smallSliderContentFive\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--작은 슬라이더 끝-->\r\n");
      out.write("\r\n");
      out.write("		<!--슬라이드 옆 광고 시작-->\r\n");
      out.write("		<div class=\"smallAdvertise\">\r\n");
      out.write("			<div class=\"smallAdvertiseCounter\"></div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"advertiseImgBox\">\r\n");
      out.write("				<div class=\"advertise\">\r\n");
      out.write("					<img src=\"img/miniadver/ad1.jpg\" alt=\"miniAd\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"advertise\">\r\n");
      out.write("					<img src=\"img/miniadver/ad2.jpg\" alt=\"miniAd\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"advertise\">\r\n");
      out.write("					<img src=\"img/miniadver/ad3.jpg\" alt=\"miniAd\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"advertise\">\r\n");
      out.write("					<img src=\"img/miniadver/ad4.jpg\" alt=\"miniAd\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"advertise\">\r\n");
      out.write("					<img src=\"img/miniadver/ad5.jpg\" alt=\"miniAd\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--슬라이드 옆 광고 끝-->\r\n");
      out.write("		<div class=\"rankingBox\">\r\n");
      out.write("			<h2>어제 베스트셀러 TOP 10 ></h2>\r\n");
      out.write("			<div class=\"rankingOneTwo\">\r\n");
      out.write("				<div class=\"oneBox\">\r\n");
      out.write("					<img src=\"img/rank/rankOne.jpg\" alt=\"rankImg\">\r\n");
      out.write("					<p style=\"color: #f32383; font-weight: bold;\">&nbsp;1&nbsp;</p>\r\n");
      out.write("					<div>\r\n");
      out.write("						<a href=\"#\">청춘의 독서 (특별증보판)</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<hr>\r\n");
      out.write("				<div class=\"twoBox\">\r\n");
      out.write("					<img src=\"img/rank/rankTwo.jpg\" alt=\"rankImg\">\r\n");
      out.write("					<p style=\"font-weight: bold;\">&nbsp;2&nbsp;</p>\r\n");
      out.write("					<div>\r\n");
      out.write("						<a href=\"#\">단 한 번의 삶</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"rankingTen\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\"><strong>3</strong>&nbsp;&nbsp;첫 여름, 완주</a></li>\r\n");
      out.write("					<li><a href=\"#\"><strong>4</strong>&nbsp;&nbsp;행동은 불안을 이긴다</a></li>\r\n");
      out.write("					<li><a href=\"#\"><strong>5</strong>&nbsp;&nbsp; 희망</a></li>\r\n");
      out.write("					<li><a href=\"#\"><strong>6</strong>&nbsp;&nbsp; 흔한남매 19</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\"><strong>7</strong>&nbsp;&nbsp;2025 제16회\r\n");
      out.write("							젊은작가상 ...</a></li>\r\n");
      out.write("					<li><a href=\"#\"><strong>8</strong>&nbsp;&nbsp;행동은 불안을 이긴다</a></li>\r\n");
      out.write("					<li><a href=\"#\"><strong>9</strong>&nbsp;&nbsp;희망</a></li>\r\n");
      out.write("					<li><a href=\"#\"><strong>10</strong>&nbsp;&nbsp;2025 큰별쌤\r\n");
      out.write("							최태성의 별★</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!--미니 이벤트 시작-->\r\n");
      out.write("		<div class=\"miniEvent\">\r\n");
      out.write("			<div class=\"miniEventCounter\"></div>\r\n");
      out.write("			<div class=\"miniEventImgBox\">\r\n");
      out.write("				<div class=\"eventImg\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/miniEvent/miniEventImg_01.jpg\"\r\n");
      out.write("						alt=\"eventImg\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"eventImg\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/miniEvent/miniEventImg_02.jpg\"\r\n");
      out.write("						alt=\"eventImg\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"eventImg\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/miniEvent/miniEventImg_03.jpg\"\r\n");
      out.write("						alt=\"eventImg\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"eventImg\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/miniEvent/miniEventImg_04.jpg\"\r\n");
      out.write("						alt=\"eventImg\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"eventImg\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/miniEvent/miniEventImg_05.jpg\"\r\n");
      out.write("						alt=\"eventImg\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"eventImg\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/miniEvent/miniEventImg_06.jpg\"\r\n");
      out.write("						alt=\"eventImg\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"eventImg\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/miniEvent/miniEventImg_07.jpg\"\r\n");
      out.write("						alt=\"eventImg\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"eventImg\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/miniEvent/miniEventImg_08.jpg\"\r\n");
      out.write("						alt=\"eventImg\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"eventImg\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/miniEvent/miniEventImg_09.jpg\"\r\n");
      out.write("						alt=\"eventImg\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"eventImg\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/miniEvent/miniEventImg_10.jpg\"\r\n");
      out.write("						alt=\"eventImg\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--미니 이벤트 끝-->\r\n");
      out.write("\r\n");
      out.write("		<!--어제 베스트셀러 TOP 10 끝-->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!--슬라이더 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 섹션 -->\r\n");
      out.write("	<section>\r\n");
      out.write("		<!-- 광고 배너 시작-->\r\n");
      out.write("		<div class=\"bookFundSlider\">\r\n");
      out.write("			<div class=\"bookFundImgWrap\">\r\n");
      out.write("				<div class=\"bookFundCounter\"></div>\r\n");
      out.write("				<div class=\"bookFundImgBox\">\r\n");
      out.write("					<div class=\"bookFundImg\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/bookFund/BookFundimg_01.png\" alt=\"\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"bookFundImg\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/bookFund/BookFundimg_02.png\" alt=\"\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"bookFundImg\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/bookFund/BookFundimg_03.png\" alt=\"\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"bookFundImg\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/bookFund/BookFundimg_04.png\" alt=\"\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 광고 배너 끝-->\r\n");
      out.write("		<!-- 한강 시작 -->\r\n");
      out.write("		<div class=\"hangangNewBookSlider\">\r\n");
      out.write("			<h2>\r\n");
      out.write("				<a href=\"#\">한강, 노벨문학상 이후 첫 책 출간예정 &gt</a>\r\n");
      out.write("			</h2>\r\n");
      out.write("			<div class=\"hangangNewBook\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 한강 끝 -->\r\n");
      out.write("		<!-- 추천 마법사 시작 -->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"recommendMagicionSlider\">\r\n");
      out.write("			<h2>\r\n");
      out.write("				<a href=\"#\">추천마법사의 선택 &gt</span></a><span\r\n");
      out.write("					style=\"font-weight: normal; font-size: 14px;\"> &nbsp;지금\r\n");
      out.write("					로그인하시면 추천마법사가 선택한 책을 보여드립니다. \r\n");
      out.write("			</h2>\r\n");
      out.write("			<div class=\"recommendMagicionBook\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 추천 마법사 끝 -->\r\n");
      out.write("		<!--화제의 책 소식 시작-->\r\n");
      out.write("		<div class=\"bookNewsSlider\">\r\n");
      out.write("			<h2>\r\n");
      out.write("				<a href=\"#\">화재의 책 소식</a>\r\n");
      out.write("			</h2>\r\n");
      out.write("			<div class=\"bookNewsBook\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--화제의 책 소식 끝-->\r\n");
      out.write("\r\n");
      out.write("		<!--이달의 주목 도서 시작-->\r\n");
      out.write("		<div class=\"thisMonthSlider\">\r\n");
      out.write("			<h2>\r\n");
      out.write("				<a href=\"#\">이달의 주목도서 &gt</a>\r\n");
      out.write("			</h2>\r\n");
      out.write("			<div class=\"thisMonthBook\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--이달의 주목 도서 끝-->\r\n");
      out.write("\r\n");
      out.write("		<!--이 주의 특가 시작 -->\r\n");
      out.write("		<div class=\"weekSaleSlider\">\r\n");
      out.write("			<h2>\r\n");
      out.write("				<a href=\"#\">이 주의 특가 &gt</a>\r\n");
      out.write("			</h2>\r\n");
      out.write("			<div class=\"weekSaleBook\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--이 주의 특가 끝-->\r\n");
      out.write("\r\n");
      out.write("		<!--알라디너 시작-->\r\n");
      out.write("		<div class=\"aladinerTv\">\r\n");
      out.write("			<div class=\"livebookTalkWrap\">\r\n");
      out.write("				<h2>\r\n");
      out.write("					<a href=\"#\">라이브 북토크 ></a>\r\n");
      out.write("				</h2>\r\n");
      out.write("				<div class=\"bookTalk\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/liveBookTalk/liveBookTalk01.jpg\"\r\n");
      out.write("						alt=\"liveBookTalk\"></a>\r\n");
      out.write("					<p class=\"liveBookTalkTitle\">\r\n");
      out.write("						<a href=\"#\"><strong>'편견 없는 유전자' 안주현 X 이정모</strong></a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"liveBookTalkHashtag\">\r\n");
      out.write("						<a href=\"#\">#라이브북토크</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"liveBookTalkHits\">라이브북토크 조회수 1,758</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"bookTalk\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/liveBookTalk/liveBookTalk02.jpg\"\r\n");
      out.write("						alt=\"liveBookTalk\"></a>\r\n");
      out.write("					<p class=\"liveBookTalkTitle\">\r\n");
      out.write("						<a href=\"#\"><strong>'메리 크리스마스, 카프카 씨' 민병훈X김태용</strong></a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"liveBookTalkHashtag\">\r\n");
      out.write("						<a href=\"#\">#라이브북토크</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"liveBookTalkHits\">라이브북토크 조회수 2,864</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"bookTalk\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/liveBookTalk/liveBookTalk03.jpg\"\r\n");
      out.write("						alt=\"liveBookTalk\"></a>\r\n");
      out.write("					<p class=\"liveBookTalkTitle\">\r\n");
      out.write("						<a href=\"#\"><strong>'고상하고 천박하게' 김사월 X 이훤 X 이슬아</strong></a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"liveBookTalkHashtag\">\r\n");
      out.write("						<a href=\"#\">#라이브북토크</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"liveBookTalkHits\">라이브북토크 조회수 1,253</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"authorMeetWrap\">\r\n");
      out.write("				<h2>\r\n");
      out.write("					<a href=\"#\">작가와의 만남 ></a>\r\n");
      out.write("				</h2>\r\n");
      out.write("				<div class=\"authorMeet\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/authorImg/authorImg01.jpg\"\r\n");
      out.write("						alt=\"authorImg\"></a>\r\n");
      out.write("					<div class=\"authorMeetContentwrap\">\r\n");
      out.write("						<p class=\"authorMeetTitle\">\r\n");
      out.write("							<a href=\"#\">&lt; 0~3세 육아, 그림책에 답이 있습니다 &gt;<br> 이임숙 작가\r\n");
      out.write("								온라인 특강\r\n");
      out.write("							</a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p class=\"authorMeetContent\">\r\n");
      out.write("							<a href=\"#\">5월 7일 (수) 오전 11시</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"authorMeet\">\r\n");
      out.write("					<a href=\"#\"><img src=\"img/authorImg/authorImg02.jpg\"\r\n");
      out.write("						alt=\"authorImg\"></a>\r\n");
      out.write("					<div class=\"authorMeetContentwrap\">\r\n");
      out.write("						<p class=\"authorMeetTitle\">\r\n");
      out.write("							<a href=\"#\">&lt; 나의 왼발 &gt; <br>6인의 저자와 함께하는 북토크\r\n");
      out.write("							</a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p class=\"authorMeetContent\">\r\n");
      out.write("							<a href=\"#\">5월 16일 (금) 오후 7시</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--알라디너 끝-->\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- 섹션 끝-->\r\n");
      out.write("\r\n");
      out.write("<!-- 푸터 임포트 -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
